TiluBee/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
    path('app/', include('users.urls')),
    path('transactions/', include('transactions.urls')),
    path('crm/', include('crm.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'crm'

urlpatterns = [
    path('auth/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('users/', views.users, name='users'),
    path('transactions/', views.transactions, name='transactions'),
    path('operators/', views.operators, name='operators'),
    path('blacklist/', views.view_blacklist, name='blacklist'),
    path('automations/<str:program>', views.automations),
    path('test/', views.test, name='test')
]

users/urls.py
from django.urls import path

from users.view.convert import ConvertView
from users.view.deposit import DepositView
from users.view.withdrawal import WithdrawalView
from users.view.wallet import WalletView
from users.view.wallet2 import Wallet2View
from users.view.settings import SettingsView


app_name = 'users'

urlpatterns = [
    path('', WalletView.as_view(), name='wallet'),
    path('wallet/', Wallet2View.as_view(), name='wallet2'),
    path('deposit/', DepositView.as_view(), name='deposit'),
    path('withdrawal/', WithdrawalView.as_view(), name='withdrawal'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('convert/', ConvertView.as_view(), name='convert')
]

crm/models.py
from django.db import models
from django.utils import timezone
from users.models import AppUser



class AdminUser(models.Model):
    first_name = models.CharField(max_length=100, default='')
    last_name = models.CharField(max_length=100, default='')
    email = models.EmailField(max_length=100, unique=True)
    phone = models.CharField(max_length=15, default='')
    password = models.CharField(max_length=100, default='')
    level = models.CharField(max_length=50, default='super admin')
    username = models.CharField(default='', max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=False)
    last_login = models.DateTimeField(default=timezone.now)
    uid = models.CharField(default='', max_length=100, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} - {self.level.title()}'

class AdminLog(models.Model):
    user = models.ForeignKey(AdminUser, on_delete=models.CASCADE)
    app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    action_type = models.CharField(max_length=100, blank=True, null=True)
    action = models.CharField(max_length=100, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"User {self.app_user.uid}, logged by {self.user.level}"


class Note(models.Model):
    user = models.ForeignKey(AdminUser, on_delete=models.CASCADE)
    app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    modified = models.BooleanField(default=False)
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(blank=True, null=True)
    super = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name}-{self.user.level} note"


class Blacklist(models.Model):
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE)
    reason = models.CharField(max_length=100, default='default')
    created_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField(blank=True, null=True)


class AccountDetails(models.Model):
    number = models.CharField(max_length=20, default='', null=True)
    bank = models.CharField(max_length=20, default='', null=True)
    name = models.CharField(max_length=20, default='', null=True)  # bank name or Binance/Bybit as uid case may be
    uid = models.CharField(default='', max_length=20, null=True)
    account_type = models.CharField(default='bank', max_length=10)  # bank, crypto, uid
    platform = models.CharField(default='', max_length=10)   # bybit, platform


class BaseWallet(models.Model):
    currency = models.CharField(max_length=20, default='')
    currency_name = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=100, default='')
    network = models.CharField(max_length=100, default='')
    key = models.CharField(max_length=500, default='')
    created_at = models.DateTimeField(default=timezone.now)


class Webhook(models.Model):
    network = models.CharField(max_length=20, default='')
    url = models.CharField(max_length=100, default='')
    webhook_id = models.CharField(max_length=100, default='')
    created_at = models.DateTimeField(default=timezone.now)

class WebhookAddress(models.Model):
    webhook = models.ForeignKey(Webhook, on_delete=models.CASCADE, related_name='addresses')
    address = models.CharField(max_length=100, default='')
    network = models.CharField(max_length=20, default='')
    created_at = models.DateTimeField(default=timezone.now)

crm/forms.py
from django import forms
from crm.models import AdminUser


class RegisterForm(forms.ModelForm):
    CHOICES = [
        ('super admin', 'Super Admin'),
        ('admin', 'Admin'),
        ('approval admin', 'Approval Admin'),
        ('team leader', 'Team Leader'),
        ('staff', 'Staff')

    ]
    level = forms.ChoiceField(choices=CHOICES)
    code = forms.CharField(max_length=20)

    class Meta:
        model = AdminUser
        fields = ['first_name', 'last_name', 'phone', 'email', 'password', 'code', 'level']

    def clean_code(self):
        if self.cleaned_data.get('code') != '1234':
            raise forms.ValidationError('Code error')


class LoginForm(forms.Form):
    phone = forms.CharField(required=True)
    password = forms.CharField(required=True)

    class Meta:
        model = AdminUser
        fields = ['phone', 'password']

users/forms.py
from django import forms
from payment_utils.tickers import COINS_DICT


class DepositForm(forms.Form):
    action = forms.ChoiceField(
        required=True,
        choices=[
            ("bank", "Bank Transfer"),
            ("uid", "UID"),
            ("crypto", "Crypto"),
            ("retrieve_bank_account", "Retrieve Bank Account"),
            ("retrieve_crypto_wallet", "Retrieve Crypto Wallet"),
            ("retrieve_uid", "Retrieve UID"),
        ],
    )
    currency = forms.CharField(required=False, max_length=10, empty_value=None)
    qty = forms.FloatField(required=False)
    platform = forms.CharField(max_length=10, required=False, empty_value=None)
    ref = forms.CharField(max_length=10, required=False, empty_value=None)
    uid = forms.CharField(max_length=10, required=False, empty_value=None)
    wallet = forms.CharField(max_length=70, required=False, empty_value=None)


class WithdrawalForm(forms.Form):
    action = forms.ChoiceField(
        required=True,
        choices=[
            ("bank", "Bank Transfer"),
            ("uid", "UID"),
            ("crypto", "Crypto"),
            ("retrieve_bank", "Retrieve Bank Account"),
        ],
    )
    currency = forms.CharField(required=False, max_length=10, empty_value=None)
    amount = forms.FloatField(required=False)
    platform = forms.CharField(max_length=10, required=False, empty_value=None)
    wallet = forms.CharField(max_length=70, required=False, empty_value=None)
    bank_id = forms.IntegerField(required=False)


class NewBankForm(forms.Form):
    number = forms.CharField(max_length=20)
    bank = forms.CharField(max_length=20)
    name = forms.CharField(max_length=50, required=False)


class SettingsForm(forms.Form):
    action = forms.ChoiceField(
        choices=[
            ("add_new_bank", "add New Bank"),
            ("avatar", "Avatar"),
            ("trash_bank", "Trash Bank"),
            ("update_password", "Update Password"),
            ("fetch_banks", "fetch Banks"),
        ],
        required=True,
    )
    value = forms.CharField(max_length=10, required=False)
    current_pass = forms.CharField(max_length=30, required=False)
    new_pass = forms.CharField(max_length=30, required=False)


class ConvertQuoteForm(forms.Form):
    action2 = forms.ChoiceField(
        choices=[("quote", "Quote"), ("confirm", "Confirm")], required=True
    )
    from_qty = forms.FloatField(required=True)
    from_coin = forms.ChoiceField(
        choices=[(coin, full) for coin, full in COINS_DICT.items()], required=True
    )
    to_coin = forms.ChoiceField(
        choices=[(coin, full) for coin, full in COINS_DICT.items()], required=True
    )


class FilterForm(forms.Form):
    action = forms.ChoiceField(
        choices=[
            ("filter", "Filter"),
            ("report", "Report"),
        ],
        required=True,
    )
    category = forms.ChoiceField(
        choices=[("all", "All"), ("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
        required=True,
    )
    duration = forms.ChoiceField(
        choices=[
            (0, "All"),
            (0.04167, "1 hr"),
            (1, "24 hours"),
            (7, "7 days"),
            (12, "12 days"),
            (30, "30 days"),
            (90, "90 days"),
            (180, "180 days"),
            (360, "360 days"),
        ],
        required=True,
    )

crm/views.py
import json
import subprocess

import requests
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt

from .forms import RegisterForm, LoginForm
from django.http import JsonResponse, HttpResponseBadRequest, HttpResponse
from crm.models import AdminUser
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import crm.utils as utils
import datetime as dt
from decouple import config
import os
from django.conf import settings
from firebase_admin import auth as firebase_auth


# Create your views here.
@login_required
def logout_user(request):
    logout(request)
    return redirect("login")


def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username=form.cleaned_data["phone"],
                password=form.cleaned_data["password"],
            )
            if user:
                login(request, user)
                return JsonResponse(
                    {"status": "success", "message": "User login successful"}
                )
            return JsonResponse(
                {"status": "error", "message": "Invalid phone or password"}
            )
        return JsonResponse({"status": "warning", "message": form.errors})
    else:
        form = LoginForm()
        return render(request, "crm/auth/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        header = request.headers.get("Authorization")
        if header:
            token = header.split("Bearer ")[1]
            try:
                user = firebase_auth.verify_id_token(token, clock_skew_seconds=10)
            except Exception as e:
                return JsonResponse({"status": "error", "message": "Invalid token"})
            else:
                user, created = AdminUser.objects.get_or_create(
                    uid=user["uid"], email=user["email"]
                )
                return JsonResponse(
                    {"status": "success", "message": "Successfully registered"}
                )
    else:
        return render(request, "crm/auth/register.html")


def dashboard(request):
    if request.user.level in ("admin", "team leader"):
        return redirect("analysis")
    elif request.user.level != "super admin":
        return redirect("loans")
    return render(request, "crm/dashboard.html")


def users(request):
    if request.method == "GET":
        return render(request, "crm/users.html")
    posted_data = {}
    for key, value in request.POST.items():
        posted_data[key] = value
    response = utils.UserUtils(request, **posted_data)
    response.process()
    return JsonResponse(
        {
            "status": response.status,
            "content": response.content,
            "message": response.message,
        }
    )


def loans(request):
    if request.method == "GET":
        return render(
            request,
            "crm/loans.html",
            {
                "app_stages": settings.APP_STAGES.keys(),
                "APP_STAGES": settings.APP_STAGES,
            },
        )
    posted_data = {}
    for key, value in request.POST.items():
        posted_data[key] = value
    response = utils.LoanUtils(request, **posted_data)
    response.process()
    return JsonResponse(
        {
            "status": response.status,
            "content": response.content,
            "message": response.message,
        }
    )


@login_required
def loans_with_status(request, status):
    if request.method == "GET":
        if status in (
            "pending",
            "approved",
            "declined",
            "disbursed",
            "overdue",
            "partpayment",
            "repaid",
        ):
            return render(request, "crm/loan_with_status.html", {"status": status})
        return HttpResponseBadRequest(status=404)


def transactions(request):
    if request.method == "GET":
        return render(request, "crm/transactions.html")
    posted_data = {}
    for key, value in request.POST.items():
        posted_data[key] = value
    response = utils.TxUtils(request, **posted_data)
    response.process()
    print(response.status)
    return JsonResponse(
        {
            "status": response.status,
            "content": response.content,
            "message": response.message,
        }
    )


@login_required
def waiver(request):
    return render(request, "crm/waiver.html")


@login_required
def view_blacklist(request):
    return render(request, "crm/blacklist.html")


@login_required
def view_logs(request):
    return render(request, "crm/logs.html")


@login_required
def accepted_users(request):
    return render(request, "crm/accepted_user.html")


@login_required
def operators(request):
    if request.method == "GET":
        return render(
            request,
            "crm/operators.html",
            {
                "app_stages": settings.APP_STAGES.keys(),
                "APP_STAGES": settings.APP_STAGES,
            },
        )
    posted_data = {}
    for key, value in request.POST.items():
        posted_data[key] = value
    response = utils.AdminUtils(request, **posted_data)
    response.process()
    return JsonResponse(
        {
            "status": response.status,
            "content": response.content,
            "message": response.message,
        }
    )


@csrf_exempt
def automations(request, program):
    if request.method == "GET":
        return JsonResponse({"status": f"success: {program}"})


@csrf_exempt
def test(request):
    return HttpResponse("Test success3")

crm/templates/crm/blacklist.html
{% extends "crm/layout.html" %}
{% load static %}

{% block title %}
    <title>Members - MG LOAN</title>
{% endblock %}

{% block search_block %}


{% endblock %}

{% block content %}

    <script>
        var overlay = $("#overlay");
        var loader = $("#loader");

        function loadOn() {
            overlay.css('display', 'block');
            loader.css('display', 'block');
        }

        function loadOff() {
            overlay.css('display', 'none');
            loader.css('display', 'none');
        }
    </script>

    <style>
        .user-online:after, .user-offline:after {
            content: "";
            position: absolute;
            bottom: 1px;
            right: 1px;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            box-shadow: 0 0 0 2px #fff;
        }

        .user-online:after {
            background: #16e15e;
        }

        .user-offline:after {
            background: #fd3550;
        }

        .user-online, .user-offline {
            position: relative;
        }


        .timeline {
            position: relative;
            padding: 20px 0;
            list-style: none;
        }

        .timeline:before {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 40px;
            width: 2px;
            content: "";
            background-color: #dee2e6;
        }

        .timeline > .timeline-item {
            position: relative;
            margin-bottom: 20px;
            padding-left: 60px;
        }

        .timeline > .timeline-item:before {
            position: absolute;
            left: 30px;
            top: 0;
            display: inline-block;
            width: 20px;
            height: 20px;
            border-radius: 50%;
            background-color: #fff;
            border: 5px solid #E65100;
            content: "";
        }

        .timeline > .timeline-item .timeline-content {
            padding: 10px;
            background-color: #fff;
            border: 1px solid #dee2e6;
            border-radius: .25rem;
        }
    </style>
    <!--start page wrapper -->
    <div class="page-wrapper">
        <div class="page-content">

            <!--end row-->

            <div class="card radius-10">
                <div class="card-body">
                    <div class="d-flex align-items-center bg-light flex-wrap p-3">
                        <div class="me-auto fw-bold fs-6">Blacklist</div>


                        <div class="d-flex align-items-center flex-wrap">
                            <div class="me-2">
                                <label for="history_month_start" class="form-label me-1">From:</label>
                                <input type="date" id="history_month_start" class="form-control d-inline-block" value=""
                                       style="width: auto;">
                            </div>
                            <div class="me-2">
                                <label for="history_month_end" class="form-label me-1">To:</label>
                                <input type="date" id="history_month_end" class="form-control d-inline-block" value=""
                                       style="width: auto;">
                            </div>
                            <div class="me-2">
                                <label for="history_rows" class="form-label me-1">Rows:</label>
                                <select id="history_rows" class="form-select d-inline-block" style="width: auto;">
                                    <option value="15">15</option>
                                    <option value="50">50</option>
                                    <option value="200">200</option>
                                    <option value="500">500</option>
                                    <option value="2000">2000</option>
                                    <option value="10000">2000+</option>
                                </select>
                            </div>

                        </div>


                        <div class="d-flex align-items-center bg-light flex-wrap">
                        <div class="me-auto fw-bold fs-6"></div>
                        <div class="d-flex align-items-center flex-wrap">

                            <div class="me-2">
                                <label for="filter" class="form-label me-1">Filters:</label>
                                <input type="text" placeholder="Search by U.ID, Phone, BVN, Fname, Lname" id="filters" class="form-control d-inline-block" value=""
                                       style="width: 22em;">
                            </div>

                            <div>
                                <button type="button" class="btn btn-primary px-3 radius-30"
                                        onclick="start(true)">Search
                                </button>
                            </div>
                        </div>
                    </div>


                    </div>

                    <hr/>
                    <div class="table-responsive">
                        <table class="table align-middle mb-0" id="example2">
                            <thead class="table-light">
                            <tr>
                                <th>
                                    <div>
										<input class="form-check-input me-3 all-checkbox border-primary border-2" type="checkbox" value="" aria-label="..." onchange="check_all_loans()">
                                        User ID
									</div>
                                </th>
                                <th>UID</th>
                                <th>Email</th>
                                <th>Date Blacklisted</th>

                            </tr>
                            </thead>
                            <tbody id="blacklist">
                            <tr>
                                <td colspan="12" style="font-weight: bold">Fetching blacklist, PLEASE WAIT ...</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--end page wrapper -->

    <input type="hidden" id="selected_user_id">





    <script>
        const success_audio = new Audio("{% static 'crm/audio/correct.mp3' %}");
        const error_audio = new Audio("{% static 'crm/audio/wrong.mp3' %}");


        var overlay = $("#overlay");
        var loader = $("#loader");
        var loader_trans = $("#loader-trans");

        function loadOn() {
            overlay.css('display', 'block');
            loader.css('display', 'block');
        }

        function onProgress(elem) {
            $('#' + elem).addClass('thin-loader')
        }

        function offProgress(elem) {
            $('#' + elem).removeClass('thin-loader')
        }

        function loadOff() {
            overlay.css('display', 'none');
            loader.css('display', 'none');
        }

        function notify(status, message) {
            if (status === "success" || status === "info") {
                success_audio.play();
            } else {
                error_audio.play();
            }
            toastr[status](message)
        }

        $('#history_month_end').change(function () {
            var start_date = new Date($("#history_month_start").val())
            var end_date = new Date($(this).val())
            if (start_date > end_date) {
                $(this).val(get_current_month())
                $("#history_month_start").val(get_current_month(-1))
                notify('warning', 'Ending date cannot be less than starting date')
            }
        })

        $('#history_month_start').change(function () {
            var end_date = new Date($("#history_month_end").val())
            var start_date = new Date($(this).val())
            if (start_date > end_date) {
                $(this).val(get_current_month(-1))
                $("#history_month_end").val(get_current_month())
                notify('warning', 'Ending date cannot be less than starting date')
            }

        })


        function start(refresh = false) {
            loadOn()
            $.ajax({
                url: "{% url 'crm:users' %}",
                type: "POST",
                data: {
                    action: 'fetch_blacklist',
                    rows: $('#history_rows').val(),
                    start: $('#history_month_start').val(),
                    end: $('#history_month_end').val(),
                    filters: $('#filters').val(),
                },
                dataType: "json",
                success: function (data) {
                    loadOff()
                    if (refresh) {
                        $('#example2').DataTable().destroy()
                    }
                    setTimeout(function () {
                        $("#blacklist").html(data.content);
                        var table = $('#example2').DataTable({
                            lengthMenu: [ [20, 70, 150, -1], [20, 70, 150, "All"] ],
                            pageLength: 15,
                            ordering: false,
                            columnDefs: [
                                {"orderable": false, "targets": 0}
                            ]
                        });
                        table.buttons().container().appendTo('#example2_wrapper .col-md-6:eq(0)');
                    }, 10)
                },
                error: function (jqXHR, errorThrown) {
                    loadOff()
                    notify('error', 'An error occurred. Page will be refreshed in 3s')
                    setTimeout(function () {
                        {#window.location.update()#}
                    }, 3000)
                },
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("Authorization", `Bearer ${localStorage.getItem('userToken')}`),
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                }
            })
        }



        $('.copy').click(function (){
            var item = $(this).data('item')
            copy_to_clipboard(item)
        })

     </script>



    <script>
        $(function () {
            $('#history_month_start').val(get_current_day(0))
            $('#history_month_end').val(get_current_day())

            start()

         
       

            $('body').on('mouseover', '.user_rows', function () {
                $(this).css({'background-color': '#E2EDFF', 'color': '#267DFD', 'cursor': 'pointer'})
            })
            $('body').on('mouseout', '.trs', function () {
                $(this).css({'background': 'white', 'color': 'black', 'cursor': 'pointer'})
            })


        })
    </script>



{% endblock %}