TiluBee/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #    path('admin/', admin.site.urls),
    path('', include('user_auth.urls')),
    path('app/', include('users.urls')),
    path('transactions/', include('transactions.urls')),
    path('crm/', include('crm.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'crm'

urlpatterns = [
    path('auth/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('users/', views.users, name='users'),
    path('transactions/', views.transactions, name='transactions'),
    path('operators/', views.operators, name='operators'),
    path('blacklist/', views.view_blacklist, name='blacklist'),
    path('automations/<str:program>', views.automations),
    path('test/', views.test, name='test')
]

user_auth/urls.py
from django.urls import path
import user_auth.views as user_auth_views
from user_auth.view.registration import RegistrationView
from user_auth.view.login import LoginView
from user_auth.view.email_verification import EmailVerificationView
from django.contrib.auth.views import LogoutView


app_name = 'user_auth'

urlpatterns = [
    path('', user_auth_views.boarding, name='board'),
    path('boarding/<int:page>', user_auth_views.boarding, name='boarding'),
    path('boarding-final/', user_auth_views.last_boarding, name='last_boarding'),
    path('auth/login', LoginView.as_view(), name='login'),
    path('accounts/login/', user_auth_views.account_login, name='loginn'),
    path('auth/register', RegistrationView.as_view(), name='register'),
    path('auth/verify-email', EmailVerificationView.as_view(), name='verify_email'),
    path('auth/logout', LogoutView.as_view(), name='logout'),
]

users/urls.py
from django.urls import path

from users.view.convert import ConvertView
from users.view.deposit import DepositView
from users.view.withdrawal import WithdrawalView
from users.view.wallet import WalletView
from users.view.wallet2 import Wallet2View
from users.view.settings import SettingsView


app_name = 'users'

urlpatterns = [
    path('', WalletView.as_view(), name='wallet'),
    path('wallet/', Wallet2View.as_view(), name='wallet2'),
    path('deposit/', DepositView.as_view(), name='deposit'),
    path('withdrawal/', WithdrawalView.as_view(), name='withdrawal'),
    path('settings/', SettingsView.as_view(), name='settings'),
    path('convert/', ConvertView.as_view(), name='convert')
]

user_auth/models.py
from django.db import models
from users.models import AppUser


class EmailVerification(models.Model):
    user = models.OneToOneField(AppUser, on_delete=models.CASCADE, related_name='email_verification')
    is_verified = models.BooleanField(default=False)
    code = models.CharField(max_length=10, null=False)
    verified_at = models.DateTimeField(auto_now=True, null=True)

user_auth/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator, RegexValidator, ValidationError
from users.models import AppUser
from django import forms


def validate_password_confirmation(form):
    password = form.cleaned_data.get('password')
    password_confirmation = form.cleaned_data.get('password_confirmation')

    if password != password_confirmation:
        raise ValidationError({"password_confirmation": "The two password fields must match."})



class RegistrationForm(forms.ModelForm):
    password_confirmation = forms.CharField(
        max_length=20, min_length=6,
        widget=forms.PasswordInput(attrs={'class': 'password-field'})
    )
    password = forms.CharField(
        max_length=20, min_length=6,
        validators=[
            RegexValidator(
                r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\.-_!\$%\(\)\=\+#]).{6,20}$',
                message="Must contain at least 1 uppercase, 1 lowercase, 1 digit, and 1 special character"
            )
        ],
        widget=forms.PasswordInput(attrs={'class': 'password-field'})
    )
    accept_terms = forms.BooleanField(required=True, widget=forms.CheckboxInput(attrs={'checked': 'checked', 'class': 'checkbox-terms tf-checkbox'}))
    email = forms.EmailField(validators=[EmailValidator], widget=forms.EmailInput(attrs={'placeholder': 'johnsmith@example.com'}))
    class Meta:
        model = AppUser
        fields = ['first_name', 'last_name', 'email', 'password', 'password_confirmation', 'accept_terms', 'phone']
        labels = {
            'first_name': 'First Name',
            'last_name': 'Last Name',
            'email': 'Email Address',
            'phone': 'Phone Number',
            'password_confirmation': 'Confirm Password',
            'password': 'Choose A Strong Password',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'John'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Smith'}),
            'phone': forms.TextInput(attrs={'placeholder': '08123456789'}),
        }

    def clean(self):
        validate_password_confirmation(self)
        return super().clean()


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email Address', required=True)
    password = forms.CharField(label='Account Password', widget=forms.PasswordInput(attrs={'class': 'password-field'}), required=True)


class EmailVerificationForm(forms.Form):
    digit1 = forms.IntegerField(required=True, max_value=9, min_value=0, widget=forms.NumberInput(attrs={
        'id': 'digit-2',
        'data-next': 'digit-3',
        'data-previous': 'digit-1'
    }))
    digit2 = forms.IntegerField(required=True, max_value=9, min_value=0, widget=forms.NumberInput(attrs={
        'id': 'digit-3',
        'data-next': 'digit-4',
        'data-previous': 'digit-2'
    }))
    digit3 = forms.IntegerField(required=True, max_value=9, min_value=0, widget=forms.NumberInput(attrs={
        'id': 'digit-4',
        'data-next': 'digit-5',
        'data-previous': 'digit-3'
    }))
    digit4 = forms.IntegerField(required=True, max_value=9, min_value=0, widget=forms.NumberInput(attrs={
        'id': 'digit-5',
        'data-next': 'digit-6',
        'data-previous': 'digit-4'
    }))

user_auth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from users.decorators import custom_login_required


# Create your views here.
def boarding(request, page=1):
    if 1 <= page <= 3 and request.method == 'GET':
        return render(request, f'user_auth/boarding{page}.html')
    return HttpResponse(status=404)


@custom_login_required
def last_boarding(request):
    return render(request, 'user_auth/boarding_last.html')


def account_login(request):
    return redirect('user_auth:login')

user_auth/templates/user_auth/boarding1.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}
    <div class="header">
      <a href="{% url 'user_auth:register' %}" class="right">Skip</a>
    </div>

    <div class="wrap-boarding">
        <div class="tf-container">
          <div class="d-flex flex-column min-vh-100 justify-content-between">
            <div class="banner-boarding mt-30">
              <img src="{% static 'user_auth/images/banner/boarding1.jpg' %}" alt="img">
              <svg xmlns="http://www.w3.org/2000/svg" width="375" height="440" viewBox="0 0 390 440" fill="none">
                <g filter="url(#filter0_f_1_12302)">
                  <path d="M317.593 220.084C162.184 337.75 264.912 337.75 199.927 337.75C134.941 337.75 260.61 361.432 82.2598 220.084C-96.0904 78.7354 134.941 102.417 199.927 102.417C264.912 102.417 473.002 102.417 317.593 220.084Z" fill="url(#paint0_linear_1_12302)"/>
                </g>
                <defs>
                  <filter id="filter0_f_1_12302" x="-84" y="0.925049" width="558" height="438.317" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                    <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                    <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                    <feGaussianBlur stdDeviation="50" result="effect1_foregroundBlur_1_12302"/>
                  </filter>
                  <linearGradient id="paint0_linear_1_12302" x1="329.25" y1="100.925" x2="182.611" y2="397.934" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#E250E5"/>
                    <stop offset="1" stop-color="#4B50E6"/>
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div class="content mb-32">
              <h2 class="text-center">Welcome to PROJECT_NAME Crypto Wallet app</h2>
              <p class="mt-8 text-center text-large">Discover the world of cryptocurrencies and manage your assets securely and conveniently.</p>
              <a href="{% url 'user_auth:boarding' page=2 %}" class="tf-btn primary md mt-40">Next </a>
              <p class="mt-20 text-center mb-35">By creating an account, you’re agree to out <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Privacy policy</a>  and <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Term of use</a> </p>
            </div>


          </div>


        </div>
    </div>

{% endblock content %}

user_auth/templates/user_auth/boarding2.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}
    <div class="header">
      <a href="{% url 'user_auth:register' %}" class="right">Skip</a>
    </div>

    <div class="wrap-boarding">
        <div class="tf-container">
          <div class="d-flex flex-column min-vh-100 justify-content-between">
            <div class="banner-boarding2 mt-20">
              <img src="{% static 'user_auth/images/banner/boarding2.jpg' %}" alt="img">
              <svg xmlns="http://www.w3.org/2000/svg" width="375" height="371" viewBox="0 0 390 371" fill="none">
                <g opacity="0.8" filter="url(#filter0_f_1_12104)">
                  <path d="M296.173 185.722C185.542 269.933 258.671 269.933 212.41 269.933C166.148 269.933 255.608 286.881 128.646 185.722C1.68354 84.5628 166.148 101.511 212.41 101.511C258.671 101.511 406.804 101.511 296.173 185.722Z" fill="url(#paint0_linear_1_12104)"/>
                </g>
                <defs>
                  <filter id="filter0_f_1_12104" x="-18.5225" y="0.443359" width="454.85" height="370.557" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                    <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                    <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                    <feGaussianBlur stdDeviation="50" result="effect1_foregroundBlur_1_12104"/>
                  </filter>
                  <linearGradient id="paint0_linear_1_12104" x1="304.471" y1="100.443" x2="199.186" y2="312.56" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#E250E5"/>
                    <stop offset="1" stop-color="#4B50E6"/>
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div class="content mb-32">
              <h2 class="text-center">Top-notch Security and Safety!</h2>
              <p class="mt-8 text-center text-large">With advanced encryption technology, your information and assets are protected with utmost security. </p>
              <a href="{% url 'user_auth:boarding' page=3 %}" class="tf-btn primary md mt-40">Next </a>
              <p class="mt-20 text-center mb-35">By creating an account, you’re agree to out <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Privacy policy</a>  and <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Term of use</a> </p>
            </div>


          </div>


        </div>
    </div>

{% endblock content %}

user_auth/templates/user_auth/boarding3.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}
    <div class="header">
      <a href="{% url 'user_auth:register' %}" class="right">Skip</a>
    </div>

    <div class="wrap-boarding">
        <div class="tf-container">
          <div class="d-flex flex-column min-vh-100 justify-content-between">
            <div class="banner-boarding2 mt-20">
              <img src="{% static 'user_auth/images/banner/boarding3.jpg' %}" alt="img">
              <svg xmlns="http://www.w3.org/2000/svg" width="375" height="335" viewBox="0 0 381 335" fill="none">
                <g opacity="0.8" filter="url(#filter0_f_1_12068)">
                  <path d="M269.131 167.427C182.034 233.37 239.606 233.37 203.186 233.37C166.765 233.37 237.195 246.642 137.241 167.427C37.2862 88.2118 166.765 101.483 203.186 101.483C239.606 101.483 356.228 101.483 269.131 167.427Z" fill="url(#paint0_linear_1_12068)"/>
                </g>
                <defs>
                  <filter id="filter0_f_1_12068" x="0.106079" y="0.647461" width="400.637" height="333.559" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                    <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                    <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                    <feGaussianBlur stdDeviation="50" result="effect1_foregroundBlur_1_12068"/>
                  </filter>
                  <linearGradient id="paint0_linear_1_12068" x1="275.664" y1="100.647" x2="193.485" y2="267.1" gradientUnits="userSpaceOnUse">
                    <stop stop-color="#E250E5"/>
                    <stop offset="1" stop-color="#4B50E6"/>
                  </linearGradient>
                </defs>
              </svg>
            </div>
            <div class="content mb-32">
              <h2 class="text-center">A Fantastic Experience with PROJECT_NAME!</h2>
              <p class="mt-8 text-center text-large">Explore the diverse features of PROJECT_NAME. Send and receive funds, track transaction history, create new wallets, and much more. </p>
              <a href="{% url 'user_auth:register' %}" class="tf-btn primary md mt-40">Get Started </a>
              <p class="mt-20 text-center mb-35">By creating an account, you’re agree to out <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Privacy policy</a>  and <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Term of use</a> </p>
            </div>


          </div>


        </div>
    </div>


{% endblock content %}

user_auth/templates/user_auth/boarding_last.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}

    <div class="pt-45 pb-16">
        <div class="tf-container">
            <div class="banner-received mt-32">
                <img src="{% static 'user_auth/images/banner/banner1.jpg' %}" alt="img">
                <svg xmlns="http://www.w3.org/2000/svg" width="350" height="350" viewBox="0 0 390 350" fill="none">
                    <g opacity="0.8" filter="url(#filter0_f_1_1747)">
                      <path d="M263.966 174.967C166.335 248.996 230.871 248.996 190.046 248.996C149.221 248.996 228.168 263.895 116.126 174.967C4.0829 86.0396 149.221 100.938 190.046 100.938C230.871 100.938 361.596 100.938 263.966 174.967Z" fill="url(#paint0_linear_1_1747)"/>
                    </g>
                    <defs>
                      <filter id="filter0_f_1_1747" x="-25.5" y="0" width="424.902" height="349.934" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
                        <feFlood flood-opacity="0" result="BackgroundImageFix"/>
                        <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
                        <feGaussianBlur stdDeviation="50" result="effect1_foregroundBlur_1_1747"/>
                      </filter>
                      <linearGradient id="paint0_linear_1_1747" x1="271.289" y1="100" x2="178.95" y2="286.752" gradientUnits="userSpaceOnUse">
                        <stop stop-color="#E250E5"/>
                        <stop offset="1" stop-color="#4B50E6"/>
                      </linearGradient>
                    </defs>
                </svg>
            </div>
            <h2 class="mt-40 text-center">Account Setup Complete.</h2>
            <p class="mt-12 text-center text-large">Your email has been confirmed, welcome to PROJECT_NAME!</p>
            <a href="{% url 'users:wallet' %}" class="tf-btn primary lg mt-40">Done</a>
        </div>
    </div>

{% endblock content %}

user_auth/templates/user_auth/email_verification.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}

    <div class="header fixed-top bg-surface d-flex justify-content-center align-items-center">
        <a href="#" class="left back-btn"><i class="icon-left-btn"></i></a>
        <h3>Email Verification</h3>
    </div>
    <div class="pt-45 pb-20">
        <div class="tf-container">
            <form class="mt-32" id="form">
                <div class="digit-group mt-12">
                    {{ form.digit1 }}
                    {{ form.digit2 }}
                    {{ form.digit3 }}
                    {{ form.digit4 }}
                </div>
                <p class="text-center text-small text-white mt-16">A code has been sent to your email</p>
                <p class="d-flex justify-content-center mt-4 text-center text-button text-primary fw-6 resend">Resend in&nbsp;<span id="countdown" ></span></p>
                <a id="submit" class="mt-40 tf-btn lg primary">Confirm</a>
            </form>

        </div>
    </div>

{% endblock content %}


{% block script %}
    <script>
        $(function (){
            startCountdown(100)
        })
    </script>

    <script>
        function startCountdown(seconds){
            countdown(seconds, 'countdown', function (){
                $('.resend').html(`Resend in&nbsp;<span id="countdown" ></span>`).css('text-decoration', 'none');
            } ,function (){
                $('.resend').attr('id', 'resend').text('Resend').css('text-decoration', 'underline');
            })
        }

        $('#submit').on('click', function(){
            event.preventDefault();
            var formData = $('#form').serialize();
            showPreloader()
            $.ajax({
              url : "{% url 'user_auth:verify_email' %}",
              type: 'POST',
              dataType: 'json',
              data: formData,
              success: function(data){
                  if(data.status === "success"){
                      window.location.href = "{% url 'user_auth:last_boarding' %}"
                  }else{
                      hidePreloader()
                      notify(data.status, data.message)
                  }
              },
                error: function(xhr, ajaxOptions, thrownError){
                  hidePreloader()
                  notify('error', xhr.status + ': ' + xhr.statusText)
                },
                beforeSend: function (xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                }
            })
        })


        $('body').on('click', '#resend', function(){
            showPreloader()
            $.ajax({
              url : "{% url 'user_auth:verify_email' %}",
              type: 'POST',
              dataType: 'json',
              data: {'operation': 'resend'},
              success: function(data){
                  hidePreloader()
                  notify(data.status, data.message)
                  $('.resend').removeAttr('id')
                  startCountdown(100)
              },
                error: function(xhr, ajaxOptions, thrownError){
                  hidePreloader()
                  notify('error', xhr.status + ': ' + xhr.statusText)
                },
                beforeSend: function (xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                }
            })
        })

    </script>
{% endblock script %}

user_auth/templates/user_auth/login.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}


    <div class="pt-45 pb-20">
        <div class="tf-container">
            <div class="mt-32">
                <h2 class="text-center">Access Your Account</h2>
            </div>
            <form class="mt-16" id="form">
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small"> {{ form.email.label }}</p>
                        {{ form.email }}
                    </label>
                </fieldset>
                <fieldset class="mt-16 mb-12">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.password.label }}</p>
                        <div class="box-auth-pass">
                            {{ form.password }}
                            <span class="show-pass">
                                <i class="icon-view"></i>
                                <i class="icon-view-hide"></i>
                            </span>
                        </div>
                    </label>
                </fieldset>
                <a href="#0" class="text-secondary">Forgot Password?</a>
                <button class="mt-20" id="submit">Login</button>
                <p class="mt-20 text-center text-small">Already have a Account? &ensp;<a href="{% url 'user_auth:register' %}">Sign up</a></p>
            </form>
        </div>
    </div>


{% endblock content %}

{% block script %}
    <script>
        $(function (){
            const flash = "{{ flash }}"
            if (flash !== ""){
                if (flash === "duplicate"){
                    notify('info', 'Duplicate login detected, please login again')
                }else if(flash === 'blacklist'){
                    notify('error', 'Account is suspended')
                }
            }
        })
    </script>

    <script>
        $('#submit').on('click', function(){
            event.preventDefault();
            var formData = $('#form').serialize();
            showPreloader()
            $.ajax({
              url : "{% url 'user_auth:login' %}",
              type: 'POST',
              dataType: 'json',
              data: formData,
              success: function(data){
                  hidePreloader()
                  if(data.status === "success"){
                      notify('success', data.message, 'Continue', '{% url "users:wallet" %}')
                  }else if(data.status === "warning"){
                      let obj = Object.entries(data.errors).at(0)
                      let title = obj.at(0).replace('_', ' ').toUpperCase()
                      let msg = `${title}: ${obj.at(1)}`
                      notify(data.status, msg)
                  }else{
                      notify(data.status, data.message)
                  }
              },
                error: function(xhr, ajaxOptions, thrownError){
                  hidePreloader()
                  notify('error', xhr.status + ': ' + xhr.statusText)
                },
                beforeSend: function (xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                }
            })
        })

    </script>

{% endblock script %}

user_auth/templates/user_auth/registration.html
{% extends 'user_auth/layout.html' %}
{% load static %}

{% block content %}

    <div class="pt-45">
        <div class="tf-container">
            <form class="mt-32 mb-16" id="form">
                <h2 class="text-center">Create New Account</h2>
                <fieldset class="mt-40">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.first_name.label }}</p>
                        {{ form.first_name }}
                    </label>
                </fieldset>
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.last_name.label }}</p>
                        {{ form.last_name }}
                    </label>
                </fieldset>
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.email.label }}</p>
                        {{ form.email }}
                    </label>
                    <p class="text-extra-small text-warning" style="font-weight: normal;">We will send a code to verify your email</p>
                </fieldset>
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.phone.label }}</p>
                        {{ form.phone }}
                    </label>
                </fieldset>
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.password.label }}</p>
                        <div class="box-auth-pass">
                            {{ form.password }}
                            <span class="show-pass">
                                <i class="icon-view"></i>
                                <i class="icon-view-hide"></i>
                            </span>
                        </div>
                    </label>
                </fieldset>
                <fieldset class="mt-16">
                    <label class="label-ip">
                        <p class="mb-8 text-small">{{ form.password_confirmation.label }}</p>
                        <div class="box-auth-pass">
                            {{ form.password_confirmation }}
                            <span class="show-pass2">
                                <i class="icon-view"></i>
                                <i class="icon-view-hide"></i>
                            </span>
                        </div>
                    </label>
                </fieldset>
                <fieldset class="group-cb cb-signup mt-12">
                    {{ form.accept_terms }}
                    <label for="cb-ip">I agree to <a href="#notiPrivacy" class="text-white" data-bs-toggle="modal">Terms and conditions</a></label>
                </fieldset>
                <button type="submit" class="mt-40" id="submit">Create an account</button>
                <p class="mt-20 text-center text-small">Already a Member? &ensp;<a href="{% url 'user_auth:login' %}">Access your account</a></p>
            </form>

        </div>
    </div>

{% endblock content %}

{% block script %}

    <script>
        $('#submit').on('click', function(){
            event.preventDefault();
            var formData = $('#form').serialize();
            showPreloader()
            $.ajax({
              url : "{% url 'user_auth:register' %}",
              type: 'POST',
              dataType: 'json',
              data: formData,
              success: function(data){
                  hidePreloader()
                  if(data.status === "success"){
                      notify('success', data.message, 'Continue', '{% url "user_auth:verify_email" %}')
                  }else{
                      let obj = Object.entries(data.errors).at(0)
                      let title = obj.at(0).replace('_', ' ').toUpperCase()
                      let msg = `${title}: ${obj.at(1)}`
                      notify(data.status, msg)
                  }
              },
                error: function(xhr, ajaxOptions, thrownError){
                  hidePreloader()
                  notify('error', xhr.status + ': ' + xhr.statusText)
                },
                beforeSend: function (xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                }
            })
        })

    </script>
{% endblock script %}

user_auth/templates/user_auth/success.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from themesflat.co/html/cointexcrypto/cointex/success.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 25 Jan 2025 10:51:24 GMT -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, viewport-fit=cover">

    <!-- font -->
    <link rel="stylesheet" href="fonts/fonts.css">
    <!-- Icons -->
    <link rel="stylesheet" href="fonts/font-icons.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet"type="text/css" href="css/styles.css"/>

   
    <!-- Favicon and Touch Icons  -->
    <link rel="shortcut icon" href="images/logo/48.png" />
    <link rel="apple-touch-icon-precomposed" href="images/logo/48.png" />

    <title>camera</title>
</head>

<body>

  
    <div class="bg-camera">
        <div class="tf-container">
            <div class="pt-30 pb-30">
                <div class="success_box">
                    <div class="icon-1 ani3">
                        <span class="circle-box lg bg-circle check-icon bg-primary"></span>
                    </div>
                    <div class="icon-2 ani5">
                        <span class="circle-box md bg-primary"></span>
                    </div>
                    <div class="icon-3 ani8">
                        <span class="circle-box md bg-primary"></span>
                    </div>
                    <div class="icon-4 ani2">
                        <span class="circle-box sm bg-primary"></span>
                    </div>
                    <h2 class="text-surface text-center">Successful!</h2>
                    <p class="text-large text-center mt-8">Your personal information has been verified</p>
                    <a href="home.html" class="tf-btn lg primary mt-40">Done</a>
                </div>
            </div>
           
                
        </div>
    </div>

    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/main.js"></script>
    
</body>

<!-- Mirrored from themesflat.co/html/cointexcrypto/cointex/success.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 25 Jan 2025 10:51:24 GMT -->
</html>